version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/Thunderbird.Client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/Thunderbird.Client.Tests"
    schedule:
      interval: "weekly"
